[package]
name = "servstat"
version = "0.0.1"
authors = ["Jared Forth <jaredforthdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.1"
reqwest = "0.10.8"
tokio-test = "0.2.1"